# Generated by Django 2.2.7 on 2019-11-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191108_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registered_user',
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_event', to='event.Event'),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_event', to='event.Event'),
        ),
    ]
