# Generated by Django 2.2.7 on 2019-11-08 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191108_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited_user',
            field=models.ManyToManyField(related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='registered_user',
            field=models.ManyToManyField(related_name='registered_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
